### PR TITLE
Fix SIGINT Handler

### PR DESCRIPTION
**Pull request by KrokodileGlue**
I don't like setjmp.

### CODE REVIEW

**Comment by alyptik** [comment]
There is "spooky action at a distance" happening when I try using ^c during the execution of infinite loops:
```c
@>>> for (;;)
@>>>
Terminating program.

[src/cepl.c:158] wtf did you do to the signal mask to hit this return???
^[[A[1]    12975 segmentation fault (core dumped)  ./cepl
./cepl
[system: 0.48s] [elapsed: 109.73s] [CPU: 2%]
[swaps: 0] ([major: 2]+[minor: 90841] pagefaults)
[input: 312]+[output: 760] ([text: 0k]+[data: 0k] [max: 285k] memory)
[exit: 0] ([voluntary: 207]+[involuntary: 6501] context-switches)
```
Strangely you manage to hit the code at L158 which is:
```c
                raise(sig);
                /* this should never be hit, but just in case */
                WARNX("%s", "wtf did you do to the signal mask to hit this return???");
                return;
```
%RIP:
> @ [#1:__strlen_avx2()] rip
> => 0x7fae2bcce661 <__strlen_avx2+17>:   vpcmpeqb (%rdi),%ymm0,%ymm1
>    0x7fae2bcce665 <__strlen_avx2+21>:   vpmovmskb %ymm1,%eax
>    0x7fae2bcce669 <__strlen_avx2+25>:   test   %eax,%eax
>    0x7fae2bcce66b <__strlen_avx2+27>:   jne    0x7fae2bcce750 <__strlen_avx2+256>
>    0x7fae2bcce671 <__strlen_avx2+33>:   add    $0x20,%rdi
>    0x7fae2bcce675 <__strlen_avx2+37>:   and    $0x1f,%ecx
>    0x7fae2bcce678 <__strlen_avx2+40>:   and    $0xffffffffffffffe0,%rdi
>    0x7fae2bcce67c <__strlen_avx2+44>:   jmp    0x7fae2bcce6b4 <__strlen_avx2+100>
>    0x7fae2bcce67e <__strlen_avx2+46>:   xchg   %ax,%ax
>    0x7fae2bcce680 <__strlen_avx2+48>:   and    $0x1f,%ecx
>    0x7fae2bcce683 <__strlen_avx2+51>:   and    $0xffffffffffffffe0,%rdi
>    0x7fae2bcce687 <__strlen_avx2+55>:   vpcmpeqb (%rdi),%ymm0,%ymm1
>    0x7fae2bcce68b <__strlen_avx2+59>:   vpmovmskb %ymm1,%eax
>    0x7fae2bcce68f <__strlen_avx2+63>:   sar    %cl,%eax
>    0x7fae2bcce691 <__strlen_avx2+65>:   test   %eax,%eax
>    0x7fae2bcce693 <__strlen_avx2+67>:   je     0x7fae2bcce6b0 <__strlen_avx2+96>
>    0x7fae2bcce695 <__strlen_avx2+69>:   tzcnt  %eax,%eax
>    0x7fae2bcce699 <__strlen_avx2+73>:   add    %rdi,%rax
>    0x7fae2bcce69c <__strlen_avx2+76>:   add    %rcx,%rax
>    0x7fae2bcce69f <__strlen_avx2+79>:   sub    %rdx,%rax

Registers:
> rax            0x77     119
> rbx            0x560b88eccb00   94607541848832
> rcx            0x0      0
> rdx            0x0      0
> rsi            0x1      1
> rdi            0x0      0
> rbp            0x7ffe9f71f550   0x7ffe9f71f550
> rsp            0x7ffe9f71f3b8   0x7ffe9f71f3b8
> r8             0x560b88eebb20   94607541975840
> r9             0x7      7
> r10            0x7ffe9f71f3c0   140731573466048
> r11            0x246    582
> r12            0x0      0
> r13            0x7ffe9f71f470   140731573466224
> r14            0x0      0
> r15            0x1b28   6952
> rip            0x7fae2bcce661   0x7fae2bcce661 <__strlen_avx2+17>
> eflags         0x10283  [ CF SF IF RF ]
> cs             0x33     51
> ss             0x2b     43
> ds             0x0      0
> es             0x0      0
> fs             0x0      0
> gs             0x0      0

Backtrace:
> #0  0x00007fae2bcce661 in __strlen_avx2 () from /usr/lib/libc.so.6
> #1  0x0000560b8748bba0 in parse_normal () at src/cepl.c:810
> #2  main (argc=<optimized out>, argv=<optimized out>) at src/cepl.c:810
> #3  0x00007fae2bb9706b in __libc_start_main () from /usr/lib/libc.so.6
> #4  0x0000560b8748d99a in _start () at /usr/include/bits/stdio2.h:97

Fault address:
> $1 = (void *) 0x3e8000032af

Trying to examine it fails, so it's probably an unmapped page:
>  0x3e8000032b7:       Cannot access memory at address 0x3e8000032b7

**Review by alyptik — CHANGES_REQUESTED** [review]
Please address the weird behavior when using ^C to stop an infinite loop and fix conflicts, thanks.

**Comment by KrokodileGlue** [comment]
It looks like certain phases of the pipeline are pretty bad at handling `SIGINT`; hitting `^C` while a program with an infinite loop is running is, as you've mentioned, pretty broken. `SIGINT` should simply kill the child processes for the program/compiler/whatever, the parent should reset all the readline stuff, and the parent should continue on its way. What actually happens is that the signal is caught by cepl and by readline (which looks like another signal in gdb), and the children live on (even with the fix for the other problem?). I don't know why it takes three `^C` to reset the repl in this condition.

The presence of both forking and readline makes dealing with signals a bit difficult. Minimal programs behave as I expect them to, but cepl doesn't. To finish the removal of `sigjmp` I'd have to sift through the readline documentation and spend time making a minimal example. Frankly, it doesn't seem worth the effort when the current `sigjmp` approach works.

**Comment by alyptik** [comment]
Understandable, thanks for the attempt, cheers.

**Pull request closed without merging**
